import './global.css';
import { Inter as FontSans } from 'next/font/google';
import { cn } from '@libs/data-access/lib/utils';

export const metadata = {
  title: 'Welcome to admin-app',
  description: 'Generated by create-nx-workspace',
};

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn(fontSans.variable)}>{children}</body>
    </html>
  );
}
